"""OpenAPI 3.1 and hardened Scalar registration."""

from hayate import Hayate
from hayate_openapi import OpenApi


def register(app: Hayate) -> None:
    OpenApi(
        app,
        title="$project_name",
        version="0.1.0",
        description="Generated by create-hayate from executable route contracts.",
    ).register(app)
