/* This file is generated by hayate-openapi. Do not edit it directly. */
import type { paths } from "./schema.js";

export interface HayateClientOptions {
  baseUrl: string | URL;
  fetch?: typeof globalThis.fetch;
  headers?: HeadersInit | (() => HeadersInit | Promise<HeadersInit>);
  credentials?: RequestCredentials;
}

export type ClientRequestInit = Omit<RequestInit, "body" | "headers" | "method"> & {
  headers?: HeadersInit;
};

type Defined<T> = Exclude<T, undefined>;
type OperationParameters<Operation> = Operation extends { parameters: infer Parameters }
  ? {
      [Location in keyof Parameters as [Defined<Parameters[Location]>] extends [never]
        ? never
        : Location]: Defined<Parameters[Location]>;
    }
  : Record<never, never>;
type RequestBody<Operation, MediaType extends string> =
  Operation extends { requestBody?: infer Body }
    ? [Defined<Body>] extends [never]
      ? never
      : Defined<Body> extends { content: infer Content }
        ? MediaType extends keyof Content
          ? Content[MediaType]
          : never
        : never
    : never;
type Responses<Operation> = Operation extends { responses: infer Value } ? Value : never;
type JsonBody<ResponseValue> =
  ResponseValue extends { content: infer Content }
    ? Content extends Record<PropertyKey, unknown>
      ? Content[keyof Content]
      : never
    : never;
export type TypedResponse<Operation> = {
  [Status in Extract<keyof Responses<Operation>, number>]:
    Omit<globalThis.Response, "json" | "status"> & {
      readonly status: Status;
      json(): Promise<JsonBody<Responses<Operation>[Status]>>;
    };
}[Extract<keyof Responses<Operation>, number>];

type Operation0 = paths["/api/health"]["get"];
type Operation0Input = OperationParameters<Operation0>;
type Operation0Response = TypedResponse<Operation0>;

type Operation1 = paths["/api/canonicalize"]["get"];
type Operation1Input = OperationParameters<Operation1>;
type Operation1Response = TypedResponse<Operation1>;

type Operation2 = paths["/api/whoami"]["get"];
type Operation2Input = OperationParameters<Operation2>;
type Operation2Response = TypedResponse<Operation2>;

type Operation3 = paths["/api/todos"]["get"];
type Operation3Input = OperationParameters<Operation3>;
type Operation3Response = TypedResponse<Operation3>;

type Operation4 = paths["/api/todos"]["post"];
type Operation4Input = OperationParameters<Operation4> & { json: RequestBody<Operation4, "application/json"> };
type Operation4Response = TypedResponse<Operation4>;

type Operation5 = paths["/api/todos/{id}"]["get"];
type Operation5Input = OperationParameters<Operation5>;
type Operation5Response = TypedResponse<Operation5>;

type Operation6 = paths["/api/todos/{id}"]["patch"];
type Operation6Input = OperationParameters<Operation6> & { json: RequestBody<Operation6, "application/json"> };
type Operation6Response = TypedResponse<Operation6>;

type Operation7 = paths["/api/todos/{id}"]["delete"];
type Operation7Input = OperationParameters<Operation7>;
type Operation7Response = TypedResponse<Operation7>;$mcp_client_types

export interface HayateClient {
  "health"(input?: Operation0Input, init?: ClientRequestInit): Promise<Operation0Response>;
  "canonicalize"(input?: Operation1Input, init?: ClientRequestInit): Promise<Operation1Response>;
  "whoami"(input?: Operation2Input, init?: ClientRequestInit): Promise<Operation2Response>;
  "listTodos"(input?: Operation3Input, init?: ClientRequestInit): Promise<Operation3Response>;
  "createTodo"(input: Operation4Input, init?: ClientRequestInit): Promise<Operation4Response>;
  "getTodo"(input: Operation5Input, init?: ClientRequestInit): Promise<Operation5Response>;
  "updateTodo"(input: Operation6Input, init?: ClientRequestInit): Promise<Operation6Response>;
  "deleteTodo"(input: Operation7Input, init?: ClientRequestInit): Promise<Operation7Response>;$mcp_client_interface
}

type InputRecord = {
  path?: Record<string, unknown>;
  query?: Record<string, unknown>;
  header?: Record<string, unknown>;
  cookie?: Record<string, unknown>;
};

function buildUrl(
  baseUrl: string | URL,
  path: string,
  query: Record<string, unknown> | undefined,
): URL {
  const base = baseUrl.toString();
  const normalizedBase = base.endsWith("/") ? base : `$${base}/`;
  const relativePath = path.startsWith("/") ? path.slice(1) : path;
  const url = new URL(relativePath, normalizedBase);
  if (query !== undefined) {
    url.search = encodeSearchValues(query).toString();
  }
  return url;
}

function encodePath(path: string, parameters: Record<string, unknown> | undefined): string {
  if (parameters !== undefined) {
    for (const [name, value] of Object.entries(parameters)) {
      if (value === undefined) {
        continue;
      }
      const encoded = Array.isArray(value)
        ? value.map((item) => encodeURIComponent(String(item))).join(",")
        : encodeURIComponent(String(value));
      path = path.replaceAll(`{$${name}}`, encoded);
    }
  }
  if (/\{[^}]+\}/u.test(path)) {
    throw new TypeError(`Hayate client is missing a path parameter for $${path}`);
  }
  return path;
}

function appendSearchValue(search: URLSearchParams, name: string, value: unknown): void {
  if (value === undefined) {
    return;
  }
  if (Array.isArray(value)) {
    for (const item of value) {
      appendSearchValue(search, name, item);
    }
    return;
  }
  search.append(name, String(value));
}

function encodeSearchValues(values: unknown): URLSearchParams {
  const search = new URLSearchParams();
  if (typeof values !== "object" || values === null || Array.isArray(values)) {
    throw new TypeError("Hayate form and query inputs must be objects");
  }
  for (const [name, value] of Object.entries(values)) {
    appendSearchValue(search, name, value);
  }
  return search;
}

async function buildHeaders(
  options: HayateClientOptions,
  input: InputRecord,
  init: ClientRequestInit,
): Promise<Headers> {
  const configured =
    typeof options.headers === "function" ? await options.headers() : options.headers;
  const headers = new Headers(configured);
  for (const [name, value] of Object.entries(input.header ?? {})) {
    if (value !== undefined) {
      headers.set(name, Array.isArray(value) ? value.join(",") : String(value));
    }
  }
  const cookies: string[] = [];
  for (const [name, value] of Object.entries(input.cookie ?? {})) {
    const values = Array.isArray(value) ? value : [value];
    for (const item of values) {
      if (item !== undefined) {
        cookies.push(`$${encodeURIComponent(name)}=$${encodeURIComponent(String(item))}`);
      }
    }
  }
  if (cookies.length > 0) {
    const existing = headers.get("cookie");
    headers.set("cookie", [existing, ...cookies].filter(Boolean).join("; "));
  }
  new Headers(init.headers).forEach((value, name) => headers.set(name, value));
  return headers;
}

function setContentType(headers: Headers, mediaType: string): void {
  if (!headers.has("content-type")) {
    headers.set("content-type", mediaType);
  }
}

export function createHayateClient(options: HayateClientOptions): HayateClient {
  const fetchImpl = options.fetch ?? globalThis.fetch;
  if (typeof fetchImpl !== "function") {
    throw new TypeError("Hayate client requires a Fetch implementation");
  }
  return {
    ["health"]: async (
      input: Operation0Input = {} as Operation0Input,
      init: ClientRequestInit = {},
    ): Promise<Operation0Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/api/health";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation0Response;
    },
    ["canonicalize"]: async (
      input: Operation1Input = {} as Operation1Input,
      init: ClientRequestInit = {},
    ): Promise<Operation1Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/api/canonicalize";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation1Response;
    },
    ["whoami"]: async (
      input: Operation2Input = {} as Operation2Input,
      init: ClientRequestInit = {},
    ): Promise<Operation2Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/api/whoami";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation2Response;
    },
    ["listTodos"]: async (
      input: Operation3Input = {} as Operation3Input,
      init: ClientRequestInit = {},
    ): Promise<Operation3Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/api/todos";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation3Response;
    },
    ["createTodo"]: async (
      input: Operation4Input,
      init: ClientRequestInit = {},
    ): Promise<Operation4Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/api/todos";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const bodyValue = input.json;
      let body: BodyInit | undefined;
      if (bodyValue !== undefined) {
        body = JSON.stringify(bodyValue);
        setContentType(headers, "application/json");
      }
      const request: RequestInit = {
        ...init,
        method: "POST",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation4Response;
    },
    ["getTodo"]: async (
      input: Operation5Input,
      init: ClientRequestInit = {},
    ): Promise<Operation5Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/api/todos/{id}";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation5Response;
    },
    ["updateTodo"]: async (
      input: Operation6Input,
      init: ClientRequestInit = {},
    ): Promise<Operation6Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/api/todos/{id}";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const bodyValue = input.json;
      let body: BodyInit | undefined;
      if (bodyValue !== undefined) {
        body = JSON.stringify(bodyValue);
        setContentType(headers, "application/json");
      }
      const request: RequestInit = {
        ...init,
        method: "PATCH",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation6Response;
    },
    ["deleteTodo"]: async (
      input: Operation7Input,
      init: ClientRequestInit = {},
    ): Promise<Operation7Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/api/todos/{id}";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "DELETE",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation7Response;
    },$mcp_client_methods
  };
}
